name: food_diary_ui_modern
description: Modern food diary UI with calorie tracking and meal cards
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  provider: ^6.1.2
  image_picker: ^1.0.7
  percent_indicator: ^4.2.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2


  # ✅ Новые зависимости для оффлайн-режима
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  connectivity_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
